import Head from 'next/head'
import Link from "next/link";
import Image from 'next/image'
import styles from '../styles/Layout.module.sass'

export default function Home() {

  return (
    <div className={ styles.container }>
      <Head>
        <title>Look Up NASA Info</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={ styles.main }>
        <h1 className={ styles.title }>
          Look through space info from <a href="https://api.nasa.gov/">NASA&apos;s APIs</a>
        </h1>
        <div className={ styles.grid }>
          <Link href={`/apodpage`}>
            <a className={ styles.card }>
              <h2>APOD &rarr;</h2>
              <p>View the Astronomy Picture of the Day.</p>
            </a>
          </Link>

          <Link href={ `/` }>
            <a className={ styles.card }>
              <h2>Earth &rarr;</h2>
              <p>Landsat imagery is provided to the public as a joint project between NASA and USGS.</p>
            </a>
          </Link>

          <Link href={ `/epic` }>
          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={ styles.card }
          >
            <h2>EPIC &rarr;</h2>
            <p>Earth Polychromatic Imaging Camera aka EPIC provides full disc imagery of the Earth and captures unique perspectives of certain astronomical events such as lunar transits.</p>
          </a>
          </Link>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={ styles.card }
          >
            <h2>InSight: Mars Weather &rarr;</h2>
            <p>
            NASA’s InSight Mars lander takes continuous weather measurements (temperature, wind, pressure) on the surface of Mars at Elysium Planitia, a flat, smooth plain near Mars’ equator.
            </p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={ styles.card }
          >
            <h2>Mars Rover Photos &rarr;</h2>
            <p>Image data gathered by NASA&apos;s Curiosity, Opportunity, and Spirit rovers on Mars. </p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={ styles.card }
          >
            <h2>NASA Image and Video Library &rarr;</h2>
            <p>Earth Polychromatic Imaging Camera aka EPIC provides full disc imagery of the Earth and captures unique perspectives of certain astronomical events such as lunar transits.</p>
          </a>
        </div>
      </main>

      <footer className={ styles.footer }>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={ styles.logo }>
            <Image src="/vercel.svg" alt="Vercel Logo" width={ 72 } height={ 16 } />
          </span>
        </a>
      </footer>
    </div>
  )
}
